Force UTF-8 locale in Cygwin CI runner
pip-compile test failed because of click requiring UTF-8 locale:
    https://github.com/sio/Makefile.venv/runs/931871726?check_suite_focus=true

Truncated traceback:

   File "/cygdrive/c/Users/RUNNER~1/AppData/Local/Temp/Makefile.venv_test_a0qd4exh/
        .venv/lib/python3.6/site-packages/click/_unicodefun.py",
   line 130, in _verify_python3_env
        " mitigation steps.{}".format(extra)
   RuntimeError: Click will abort further execution because Python 3 was
        configured to use ASCII as encoding for the environment. Consult
        https://click.palletsprojects.com/python3/ for mitigation steps.
    This system supports the C.UTF-8 locale which is recommended. You might be
    able to resolve your issue by exporting the following environment
    variables:
        export LC_ALL=C.UTF-8 export LANG=C.UTF-8